# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wms_msg_snd_ui_2.1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(839, 620)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, -140, 381, 371))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Downloads/logo_new.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 560, 241, 31))
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 57 12pt \"Ubuntu Light\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 570, 231, 21))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(740, 480, 101, 211))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Downloads/home android.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 110, 681, 61))
        self.textEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(120, 120, 120);\n"
"font: 75 12pt \"Ubuntu Mono\";")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 190, 541, 61))
        self.textEdit_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(120, 120, 120);\n"
"font: 75 12pt \"Ubuntu Mono\";")
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(700, 110, 131, 61))
        self.pushButton_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 57 12pt \"Ubuntu Light\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 300, 861, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-10, 530, 861, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 330, 751, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(560, 190, 131, 61))
        self.pushButton_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 57 12pt \"Ubuntu Light\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(700, 190, 131, 61))
        self.pushButton_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 57 12pt \"Ubuntu Light\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 260, 641, 18))
        self.label_4.setStyleSheet("color: rgb(153, 153, 153);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 280, 641, 18))
        self.label_5.setStyleSheet("color: rgb(153, 153, 153);")
        self.label_5.setObjectName("label_5")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(750, 260, 61, 41))
        self.textEdit_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(120, 120, 120);\n"
"font: 75 12pt \"Ubuntu Mono\";")
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(667, 260, 71, 31))
        self.label_6.setObjectName("label_6")
        self.label_3.raise_()
        self.label.raise_()
        self.pushButton_4.raise_()
        self.label_2.raise_()
        self.textEdit.raise_()
        self.textEdit_2.raise_()
        self.pushButton_5.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.textBrowser.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.textEdit_3.raise_()
        self.label_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "SEND"))
        self.label_2.setText(_translate("MainWindow", "ictfromabc-CREW#2022AL"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "ENTER GROUP NAME"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "ENTER THE MESSAGE"))
        self.pushButton_5.setText(_translate("MainWindow", "Search Group"))
        self.textBrowser.setPlaceholderText(_translate("MainWindow", "Waiting For Data..."))
        self.pushButton_6.setText(_translate("MainWindow", "Select Image"))
        self.pushButton_7.setText(_translate("MainWindow", "Select Audio"))
        self.label_4.setText(_translate("MainWindow", "File Select"))
        self.label_5.setText(_translate("MainWindow", "File Select"))
        self.textEdit_3.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "GroupSkip"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
